version: "3.9"
services:
  neo4j:
    image: neo4j:5.18-community
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/test1234"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:

